=== rdelromero/Lenguajesdemarcas_AD2_Ricardo/biblioteca.dtd
<!ELEMENT biblioteca (comentario,libros,revistas,periódicos)>

<!ELEMENT comentario (#PCDATA)>

<!ELEMENT libros (libro+)>
   <!ELEMENT libro (l_título, capítulos, l_índice, sinopsis)>
      <!ATTLIST libro
         tipo_clase (novela|infantil|didáctico) #REQUIRED
         Id ID #REQUIRED
         autor NMTOKENS #IMPLIED
         edición NMTOKEN #REQUIRED
         nombre_editorial NMTOKEN #IMPLIED
         n_páginas NMTOKEN #IMPLIED
      >
      <!ELEMENT l_título (#PCDATA)>
      <!ELEMENT capítulos (capítulo+)>
         <!ELEMENT capítulo (c_título, c_contenido)>
            <!ATTLIST capítulo
               idcap ID #REQUIRED
               n_páginas NMTOKEN #IMPLIED
            >
            <!ELEMENT c_título (#PCDATA)>
            <!ELEMENT c_contenido EMPTY>
               <!ATTLIST c_contenido
                  enlace CDATA #IMPLIED
               >
      <!ELEMENT l_índice (#PCDATA)>
      <!ELEMENT sinopsis (#PCDATA)>

<!ELEMENT revistas (revista+)>
   <!ELEMENT revista (r_título, n_revista, índice_de_contenido, r_secciones)>
      <!ATTLIST revista
         Id ID #REQUIRED 
         tipo_clase (informática|corazón|coches|investigación|otras) #REQUIRED
         n_páginas NMTOKEN #IMPLIED
      >
      <!ELEMENT r_título (#PCDATA)>
      <!ELEMENT n_revista (#PCDATA)>
      <!ELEMENT índice_de_contenido (#PCDATA)>      
      <!ELEMENT r_secciones (r_sección+)>
         <!ELEMENT r_sección (s_título, s_contenido)>
            <!ATTLIST r_sección
               idsec ID #REQUIRED
               n_páginas NMTOKEN #IMPLIED
            >
            <!ELEMENT s_título (#PCDATA)>
            <!ELEMENT s_contenido EMPTY>
               <!ATTLIST s_contenido
                  enlace CDATA #IMPLIED
               >
                           

<!ELEMENT periódicos (periódico+)>
   <!ELEMENT periódico (p_índice, p_secciones)>
      <!ATTLIST periódico
         Id ID #REQUIRED 
         tipo_clase (nacional|internacional) #REQUIRED
         nombre NMTOKENS #REQUIRED
         fecha_publicación NMTOKEN #REQUIRED
         n_páginas NMTOKEN #IMPLIED
      >
      <!ELEMENT p_índice (#PCDATA)>   
      <!ELEMENT p_secciones (p_sección+)>
         <!ELEMENT p_sección (artículo+)>
            <!ATTLIST p_sección
               tipo_sección (opinión|nacional|internacional|económica|deportes) #REQUIRED
               n_páginas NMTOKEN #IMPLIED
            >
            <!ELEMENT artículo (a_título, a_contenido)>
               <!ATTLIST artículo
                  autor NMTOKENS #IMPLIED
               >
            <!ELEMENT a_título (#PCDATA)>
            <!ELEMENT a_contenido EMPTY>
               <!ATTLIST a_contenido
                  enlace CDATA #IMPLIED
               >

=== rdelromero/Lenguajesdemarcas_AD2_Ricardo/bibliotecareferenciadtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Lenguajes de marcas Actividad de desarrollo 2-->
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd" [
   <!ENTITY PRSO "Redacción de sección Opinión">
]>

<biblioteca>
<comentario>
   Existen tres tipos de documentos almacenados en la biblioteca: libros, revistas y periódicos
.
</comentario>
   
<libros>
   <!-- Un ejemplar de libro infantil -->
   <libro tipo_clase="infantil" Id="L0001" autor="Juan Muñoz Martín" edición="18" nombre_editorial="SM" n_páginas="126">
      <l_título>Fray Perico y su borrico</l_título>
      <capítulos>
         <capítulo idcap="Cap1" n_páginas="4">
            <c_título>Esto eran veinte frailes</c_título>
            <c_contenido enlace="https://www..."></c_contenido>
         </capítulo>
         <capítulo idcap="Cap2" n_páginas="4">
            <c_título>Fray Perico</c_título>
            <c_contenido enlace="https://www..."></c_contenido>
         </capítulo>
         <capítulo idcap="Cap29" n_páginas="6">
            <c_título>La campana</c_título>
            <c_contenido enlace="https://www..."></c_contenido>
         </capítulo>
      </capítulos>            
      <l_índice>
          1 Esto eran veinte frailes, 2 Fray Perico, [...], 29 La campana
      </l_índice>
      <sinopsis>
         Esto eran veinte frailes, en un antiguo convento cerquita de Salamanca. [...].
      </sinopsis>
   </libro>
</libros>
      
<revistas>
   <!-- Un ejemplar de revista informática -->
   <revista Id="R0001" tipo_clase="informática" n_páginas="202">
      <!-- titulo y n_revista tendrían más sentido como atributo, pero el enunciado los exige elemento -->
      <r_título>
         PC Actual
      </r_título>
      <n_revista>
         128
      </n_revista>
      <índice_de_contenido>
         0 Opinión, 1 Actualidad, 2 VNU Labs, 3 Mundo Mac, [...], 9 Club PC Actual
      </índice_de_contenido>
      <r_secciones>
         <r_sección idsec="Sec0" n_páginas="3">
            <s_título>Opinión</s_título>
            <s_contenido enlace="https://archive.org/details/pc-actual-128/page/n7"></s_contenido>
         </r_sección>
         <r_sección idsec="Sec1" n_páginas="48">
            <s_título>Actualidad</s_título>
            <s_contenido enlace="https://archive.org/details/pc-actual-128/page/n9"></s_contenido>
         </r_sección>
         <r_sección idsec="Sec2" n_páginas="37">
            <s_título>VNU Labs</s_título>
            <s_contenido enlace="https://archive.org/details/pc-actual-128/page/n57"></s_contenido>
         </r_sección>
         <r_sección idsec="Sec3" n_páginas="5">
            <s_título>Mundo Mac</s_título>
            <s_contenido enlace="https://archive.org/details/pc-actual-128/page/n95"></s_contenido>
         </r_sección>
         <r_sección idsec="Sec9" n_páginas="7">
            <s_título>Club PC Actual</s_título>
            <s_contenido enlace="https://archive.org/details/pc-actual-128/page/n195"></s_contenido>
         </r_sección>
      </r_secciones>               
   </revista>
</revistas>

<periódicos>
   <!-- Un ejemplar de periódico nacional -->
   <periódico Id="P0001" tipo_clase="nacional" nombre="ABC" fecha_publicación="2003-08-25" n_páginas="92">
      <p_índice>
         1 Opinión, 2 Nacional, 3 Internacional, 4 Económica, 5 Deportes
      </p_índice>
      <p_secciones>
         <p_sección tipo_sección="opinión" n_páginas="5">
            <artículo autor="&PRSO;">
               <a_título>El referéndum que Chávez no quiere</a_título>
               <a_contenido enlace="https://www.abc.es/opinion/abci-referendum-chavez-no-quiere-200308250300-203435_noticia.html"></a_contenido>
            </artículo>
            <artículo autor="&PRSO;">
               <a_título>Auge de los deportistas españoles</a_título>
               <a_contenido enlace="https://www.abc.es/opinion/abci-auge-deportistas-espanoles-200308250300-203434_noticia.html"></a_contenido>
            </artículo>
         </p_sección>
         <p_sección tipo_sección="nacional" n_páginas="8">
            <artículo autor="María Jesús Cañizares">
               <a_título>Las dos caras del PSC</a_título>
               <a_contenido enlace="https://www.abc.es/espana/abci-caras-200308250300-203307_noticia.html"></a_contenido>
            </artículo>
         </p_sección>
         <p_sección tipo_sección="internacional" n_páginas="7">
            <artículo autor="Luis de Vega">
               <a_título>La cuna de los chiíes se tiñe de sangre con el asesinato del ayatolá Al Hakim</a_título>
               <a_contenido enlace="https://www.abc.es/internacional/abci-cuna-chiies-tine-sangre-intento-asesinato-ayatola-hakim-200308250300-203319_noticia.html"></a_contenido>
            </artículo>
         </p_sección>
      </p_secciones>               
   </periódico>
</periódicos>

</biblioteca>
