=== rdelromero/Lenguajesdemarcas_AD2_Ricardo/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--El elemento biblioteca NO contiene solo texto así que es complexType. Aparece exactamente una vez.
Los elementos hijos de biblioteca deberán aparecer en orden por lo que empleados el indicador de orden
sequence. El orden será: comentario, libros, revistas, periódicos.-->
<xs:element name="biblioteca">
   <xs:complexType>
   <xs:sequence>
   
   <!--El elemento comentario contiene solo texto así que es simplexType. Aparece exactamente una vez.-->
   <xs:element name="comentario"/>
   
   <!--El elemento libros tiene los siguientes hijos y en este orden: libro-->
   <xs:element name="libros">
      <xs:complexType>
      <xs:sequence>
      <!--El elemento libro tiene los siguientes hijos y en este orden: título, capítulos, índice, sinopsis.
      El elemento libro tiene por atributos tipo_clase, Id, autor, edición, nombre_editorial y n_páginas-->
      <xs:element name="libro" maxOccurs="unbounded">
         <xs:complexType>
         <xs:sequence>
         <xs:element name="título" type="xs:string"/>
         <!--El elemento capítulos tiene los siguientes hijos y en este orden: capítulo-->
         <xs:element name="capítulos">
            <xs:complexType>
            <xs:sequence>
            <!--El elemento capítulo tiene los siguientes hijos y en este orden: título, contenido.
            El elemento capítulo tiene por atributos idcap y n_páginas-->
            <xs:element name="capítulo" maxOccurs="unbounded">
               <xs:complexType>
               <xs:sequence>
               <!--El elemento título solo tiene texto y aparece entre 0 y 1 veces-->
               <xs:element name="título" type="xs:string" minOccurs="0"/>
               <!--El elemento contenido no tiene hijos y tiene un único atributo llamado enlace-->
               <xs:element name="contenido">               
                  <xs:complexType>
                  <xs:attribute name="enlace" type="xs:string"/>            
                  </xs:complexType>
               </xs:element>
               </xs:sequence>
               <xs:attribute name="idcap" type="xs:string" use="required"/>
               <xs:attribute name="n_páginas" type="xs:positiveInteger"/>
               </xs:complexType>
            </xs:element>
            </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="índice" type="xs:string"/>
         <xs:element name="sinopsis" type="xs:string"/>
         </xs:sequence>
         <!--El atributo tipo_clase debe aparecer y debe ser uno de entre novela, infantil, didáctico-->
         <xs:attribute name="tipo_clase" use="required">
            <xs:simpleType>
            <xs:restriction base="xs:string">
               <xs:pattern value="novela|infantil|didáctico"/>
               <!-- Otra opción equivalente sería
                xs:enumeration value="novela"/>
               <xs:enumeration value="infantil"/>
               <xs:enumeration value="didáctico"/> -->
            </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <!--El atributo Id debe aparecer y consta de 5 caracteres siendo el primero de ellos la letra L y
         los cuatro siguientes dígitos-->
         <xs:attribute name="Id" use="required">
            <xs:simpleType>
            <xs:restriction base="xs:string">
               <xs:pattern value="L[0-9][0-9][0-9][0-9]"/>
            </xs:restriction>
            </xs:simpleType>
         </xs:attribute>   
         <xs:attribute name="autor" type="xs:string"/>
         <xs:attribute name="año_edición" type="xs:gYear" use="required"/>
         <xs:attribute name="nombre_editorial" type="xs:string"/>
         <xs:attribute name="n_páginas" type="xs:positiveInteger"/>    
         </xs:complexType>
      </xs:element>
      </xs:sequence>
      </xs:complexType>   
   </xs:element>
   
   <xs:element name="revistas">
      <xs:complexType>
      <xs:sequence>
      <xs:element name="revista" maxOccurs="unbounded">
         <xs:complexType>
         <xs:sequence>
         <xs:element name="título" type="xs:string"/>
         <xs:element name="n_revista" type="xs:positiveInteger"/>
         <xs:element name="índice_de_contenido" type="xs:string"/>
         <xs:element name="secciones">
            <xs:complexType>
            <xs:sequence>
            <xs:element name="sección" maxOccurs="unbounded">
               <xs:complexType>
               <xs:sequence>
               <xs:element name="título" type="xs:string"/>
               <xs:element name="contenido">
                  <xs:complexType>
                  <xs:attribute name="enlace" type="xs:string"/>            
                  </xs:complexType>
               </xs:element>
               </xs:sequence>
               <xs:attribute name="idsec" type="xs:nonNegativeInteger" use="required"/>
               <xs:attribute name="n_páginas" type="xs:positiveInteger"/>
               </xs:complexType>
            </xs:element>
            </xs:sequence>
            </xs:complexType>
        </xs:element>
        </xs:sequence>
        <xs:attribute name="Id" use="required">
            <xs:simpleType>
            <xs:restriction base="xs:string">
               <xs:pattern value="R([a-zA-Z0-9])*"/>
            </xs:restriction>
            </xs:simpleType>
         </xs:attribute> 
         <xs:attribute name="tipo_clase" use="required">
   
            <xs:simpleType>
            <xs:restriction base="xs:string">
               <xs:pattern value="informática|corazón|coches|investigación|otras"/>
            </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="n_páginas" type="xs:positiveInteger"/>  
         </xs:complexType>
      </xs:element>
      </xs:sequence>
      </xs:complexType>     
   </xs:element>
   
   <xs:element name="periódicos">
      <xs:complexType>
      <xs:sequence>
      <xs:element name="periódico" maxOccurs="unbounded">
         <xs:complexType>
         <xs:sequence>
         <xs:element name="índice" type="xs:string"/>
         <xs:element name="secciones">
            <xs:complexType>
            <xs:sequence>
            <xs:element name="sección" maxOccurs="unbounded">
               <xs:complexType>
               <xs:sequence>
               <xs:element name="artículo" maxOccurs="unbounded">
                  <xs:complexType>
                  <xs:sequence>
                  <xs:element name="título" type="xs:string"/>
                  <xs:element name="contenido">
                     <xs:complexType>
                     <xs:attribute name="enlace" type="xs:string"/>            
                     </xs:complexType>
                  </xs:element>
                  </xs:sequence>
                  <xs:attribute name="autor" type="xs:string"/>  
                  </xs:complexType>
               </xs:element>
               </xs:sequence>
               <xs:attribute name="tipo_sección" use="required">
                  <xs:simpleType>
                  <xs:restriction base="xs:string">
                     <xs:pattern value="opinión|nacional|internacional|económica|deportes"/>
                  </xs:restriction>
                  </xs:simpleType>
               </xs:attribute>
               <xs:attribute name="n_páginas" type="xs:positiveInteger"/>   
               </xs:complexType>   
            </xs:element>
            </xs:sequence>
            </xs:complexType>
         </xs:element>
         </xs:sequence>
         <xs:attribute name="Id" use="required">
            <xs:simpleType>
            <xs:restriction base="xs:string">
               <xs:pattern value="P[0-9][0-9][0-9][0-9]"/>
            </xs:restriction>
            </xs:simpleType>            
         </xs:attribute>
         <xs:attribute name="tipo_clase" use="required">   
            <xs:simpleType>
            <xs:restriction base="xs:string">
               <xs:pattern value="nacional|internacional"/>
            </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="nombre" type="xs:string" use="required"/>
         <xs:attribute name="fecha_publicación" type="xs:date" use="required"/>
         <xs:attribute name="n_páginas" type="xs:positiveInteger"/>    
         </xs:complexType>
      </xs:element>
      </xs:sequence>
      </xs:complexType>
   </xs:element>
   
   </xs:sequence>
   </xs:complexType>
</xs:element>
   
</xs:schema>

=== rdelromero/Lenguajesdemarcas_AD2_Ricardo/bibliotecareferenciaxsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca [
   <!ENTITY PRSO "Redacción de sección Opinión">
]>
<biblioteca xsi:noNamespaceSchemaLocation="biblioteca.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<comentario>
   Existen tres tipos de documentos almacenados en la biblioteca: libros, revistas y periódicos.
</comentario>
<libros>
    <!-- Un ejemplar de libro infantil -->
	<libro tipo_clase="infantil" Id="L0001" autor="Juan Muñoz Martín" edición="18" nombre_editorial="SM" n_páginas="126">
		<título>Fray Perico y su borrico</título>
		<capítulos>
			<capítulo idcap="1" n_páginas="4">
				<título>Esto eran veinte frailes</título>
				<contenido enlace="https://www..."/>
			</capítulo>
			<capítulo idcap="2" n_páginas="4">
				<título>Fray Perico</título>
				<contenido enlace="https://www..."/>
			</capítulo>
			<capítulo idcap="29" n_páginas="6">
				<título>La campana</título>
				<contenido enlace="https://www..."/>
			</capítulo>
		</capítulos>
		<índice>
		    1 Esto eran veinte frailes, 2 Fray Perico, [...], 29 La campana
        </índice>
		<sinopsis>
            Esto eran veinte frailes, en un antiguo convento cerquita de Salamanca. [...].
        </sinopsis>
	</libro>
</libros>
    <revistas><!-- Un ejemplar de revista informática -->
		<revista Id="R0001" tipo_clase="informática" n_páginas="202"><!-- titulo y n_revista tendrían más sentido como atributo, pero el enunciado los exige elemento -->
			<título>
                PC Actual
            </título>
			<n_revista>
                128
            </n_revista>
			<índice_de_contenido>
                0 Opinión, 1 Actualidad, 2 VNU Labs, 3 Mundo Mac, [...], 9 Club PC Actual
            </índice_de_contenido>
			<secciones>
			    <sección idsec="0" n_páginas="3">
					<título>Opinión</título>
					<contenido enlace="https://archive.org/details/pc-actual-128/page/n7"/>
				</sección>
				<sección idsec="1" n_páginas="48">
					<título>Actualidad</título>
					<contenido enlace="https://archive.org/details/pc-actual-128/page/n9"/>
				</sección>
				<sección idsec="2" n_páginas="37">
					<título>VNU Labs</título>
					<contenido enlace="https://archive.org/details/pc-actual-128/page/n57"/>
				</sección>
				<sección idsec="3" n_páginas="5">
					<título>Mundo Mac</título>
					<contenido enlace="https://archive.org/details/pc-actual-128/page/n95"/>
				</sección>
				<sección idsec="9" n_páginas="7">
					<título>Club PC Actual</título>
					<contenido enlace="https://archive.org/details/pc-actual-128/page/n195"/>
				</sección>
			</secciones>
		</revista>
	</revistas>
<periódicos><!-- Un ejemplar de periódico nacional -->
	<periódico Id="P0001" tipo_clase="nacional" nombre="ABC" fecha_publicación="2003-08-25" n_páginas="92">
		<índice>
		    1 Opinión, 2 Nacional, 3 Internacional, 4 Económica, 5 Deportes
        </índice>
		<secciones>
			<sección tipo_sección="opinión" n_páginas="5">
				<artículo autor="Redacción de sección Opinión">
					<título>El referéndum que Chávez no quiere</título>
					<contenido enlace="https://www.abc.es/opinion/abci-referendum-chavez-no-quiere-200308250300-203435_noticia.html"/>
				</artículo>
				<artículo autor="Redacción de sección Opinión">
					<título>Auge de los deportistas españoles</título>
					<contenido enlace="https://www.abc.es/opinion/abci-auge-deportistas-espanoles-200308250300-203434_noticia.html"/>
				</artículo>
			</sección>
			<sección tipo_sección="nacional" n_páginas="8">
				<artículo autor="María Jesús Cañizares">
					<título>Las dos caras del PSC</título>
					<contenido enlace="https://www.abc.es/espana/abci-caras-200308250300-203307_noticia.html"/>
				</artículo>
			</sección>
			<sección tipo_sección="internacional" n_páginas="7">
				<artículo autor="Luis de Vega">
					<título>La cuna de los chiíes se tiñe de sangre con el asesinato del ayatolá Al Hakim</título>
					<contenido enlace="https://www.abc.es/internacional/abci-cuna-chiies-tine-sangre-intento-asesinato-ayatola-hakim-200308250300-203319_noticia.html"/>
				</artículo>
			</sección>
		</secciones>
	</periódico>
</periódicos>
</biblioteca>
